"""create initial tables

Revision ID: 3178c9e20759
Revises: b634123ae926
Create Date: 2025-09-17 02:13:29.841147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3178c9e20759'
down_revision = 'b634123ae926'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
