"""test1

Revision ID: 5f083b88a37b
Revises: 6005f4daa38d
Create Date: 2025-09-16 01:10:16.058564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f083b88a37b'
down_revision = '6005f4daa38d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
