"""'test'

Revision ID: 6005f4daa38d
Revises: f0c2352cbade
Create Date: 2025-09-16 00:13:41.371883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6005f4daa38d'
down_revision = 'f0c2352cbade'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
