"""create initial tables

Revision ID: 6b93f093a9cc
Revises: f9e2a6b4cdb1
Create Date: 2025-09-15 23:49:44.806294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b93f093a9cc'
down_revision = 'f9e2a6b4cdb1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
