"""add category.budget_links relationship

Revision ID: a6f8a6b97790
Revises: 5f083b88a37b
Create Date: 2025-09-16 01:21:08.266028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6f8a6b97790'
down_revision = '5f083b88a37b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
