"""create initial tables

Revision ID: a7e32282240d
Revises: 3178c9e20759
Create Date: 2025-09-17 09:41:31.524634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e32282240d'
down_revision = '3178c9e20759'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
