"""add category.budget_links relationship

Revision ID: b634123ae926
Revises: a6f8a6b97790
Create Date: 2025-09-16 01:54:59.794470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b634123ae926'
down_revision = 'a6f8a6b97790'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
